Repository FlightControl-Master/MOOSE, pull requests merged in 2018-06, with the labels that each got.

#923 Feature/zone unit offsets
  Moose Development/Moose/Core/Zone.lua
Labels: enhancement

#936 Improvments and New Features
  Moose Development/Moose/Core/Database.lua
  Moose Development/Moose/Core/Point.lua
  Moose Development/Moose/Core/Spawn.lua
  Moose Development/Moose/DCS.lua
  Moose Development/Moose/Functional/RAT.lua
  Moose Development/Moose/Utilities/Utils.lua
  Moose Development/Moose/Wrapper/Airbase.lua
Labels: enhancement, hard work, implemented, ready for testing

#940 SPAWN set correct initial heading
  Moose Development/Moose/Core/Spawn.lua
Labels: fixed
